### ISSUE TITLE
Cast Exception with .NET 3.5

### ISSUE THREAD

**Issue by paco3346** [MonoMod/MonoMod.Common#24]
Background: I'm trying to work with Harmony in a net35 project but the pre-compiled version of harmony was having issues so I decided to build from source.

I'm having this cast error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'HarmonyLib.HarmonySharedState' threw an exception. ---> System.InvalidCastException: Unable to cast object of type 'System.Reflection.CerArrayList`1[System.Reflection.RuntimePropertyInfo]' to type 'System.Array'.
   at MonoMod.Utils.ReflectionHelper._GetArray(Object cache, MethodInfo getter)
   at MonoMod.Utils.ReflectionHelper.FixReflectionCache(Type type)
   at MonoMod.Utils.ReflectionHelper.FixReflectionCacheAuto(Type type)
   at MonoMod.Utils.DynamicMethodDefinition.<>c__DisplayClass3_0.<_CopyMethodToDefinition>g__ResolveTokenAs|1(Int32 token, TokenResolutionMode resolveMode)
   at MonoMod.Utils.DynamicMethodDefinition.<>c__DisplayClass3_0.<_CopyMethodToDefinition>g__ReadOperand|0(BinaryReader reader, Instruction instr)
   at MonoMod.Utils.DynamicMethodDefinition._CopyMethodToDefinition()
   at MonoMod.Utils.DynamicMethodDefinition.Reload()
   at MonoMod.Utils.DynamicMethodDefinition..ctor(MethodBase method)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at HarmonyLib.HarmonySharedState..cctor() in C:\redacted\Harmony-2.2.1.0\Harmony\Internal\HarmonySharedState.cs:line 73
   --- End of inner exception stack trace ---
```

The real struggle is that `CerArrayList` is an internal sealed class so I can't think of any way to properly cast without tons more reflection work (nor does it have any `ToArray()` convenience methods). The following is the method responsible for invoking the methods I'm having trouble with (GetFieldList, GetPropertyList). Do these just have a totally different signature in newer versions of .NET?

https://github.com/MonoMod/MonoMod.Common/blob/1d139593392a300be82847ff1bc01fa4364d5a3e/Utils/ReflectionHelper.FixReflectionCache.cs#L172-L176

**Comment by 0x0ade** [comment]
Thank you for the detailed report. Nowadays I'm usually seeing .NET Framework 3.5 as a compilation target for older Unity games (which use mono), but never as an actual runtime, therefore many of its quirks go unnoticed.

 If you're able to build from source and test yourself, can you please check if this works? If not: that's fine, that'll just mean that I'll have to find some spare time to test this myself next week 😅

```diff
diff --git a/Utils/ReflectionHelper.FixReflectionCache.cs b/Utils/ReflectionHelper.FixReflectionCache.cs
index 6a91a1c..e0a98c3 100644
--- a/Utils/ReflectionHelper.FixReflectionCache.cs
+++ b/Utils/ReflectionHelper.FixReflectionCache.cs
@@ -45,6 +45,8 @@ namespace MonoMod.Utils {
             .GetType("System.RuntimeType+RuntimeTypeCache")
             ?.GetMethod("GetPropertyList", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
 
+        private static Dictionary<Type, FieldInfo> fmap_CerArrayList_array = new Dictionary<Type, FieldInfo>();
+
 #if !NETFRAMEWORK3
         private static readonly ConditionalWeakTable<Type, CacheFixEntry> _CacheFixed = new ConditionalWeakTable<Type, CacheFixEntry>();
 #else
@@ -172,7 +174,24 @@ namespace MonoMod.Utils {
         private static Array _GetArray(object cache, MethodInfo getter) {
             // Get and discard once, otherwise we might not be getting the actual backing array.
             getter.Invoke(cache, _CacheGetterArgs);
-            return (Array) getter.Invoke(cache, _CacheGetterArgs);
+
+            object arrayRaw = getter.Invoke(cache, _CacheGetterArgs);
+            if (arrayRaw is Array array)
+                return array;
+
+            // .NET Framework 3.5 is weird.
+            Type arrayType = arrayRaw.GetType();
+            if (arrayType.IsGenericType && !arrayType.IsGenericTypeDefinition) {
+                Type arrayTypeGeneric = arrayType.GetGenericTypeDefinition();
+
+                if (arrayTypeGeneric.FullName == "System.Reflection.CerArrayList`1") {
+                    if (!fmap_CerArrayList_array.TryGetValue(arrayType, out FieldInfo f_CerArrayList_array))
+                        fmap_CerArrayList_array[arrayType] = f_CerArrayList_array = arrayType.GetField("m_array", BindingFlags.NonPublic | BindingFlags.Instance);
+                    return (Array) f_CerArrayList_array.GetValue(arrayRaw);
+                }
+            }
+
+            throw new NotSupportedException($"Unsupported reflection cache array type: {arrayRaw?.GetType().FullName ?? "null"}");
         }
 
         private static void _FixReflectionCacheOrder<T>(Array orig) where T : MemberInfo {

```

**Comment by 0x0ade** [comment]
Just had some time to write a quick standalone test application for this myself, and found another problem. 225c3d4499894f940e2b72bd11cf060763869318 should solve the issue, it'll be available in the next MonoMod.Common version, can't say when Harmony will update to it though.

**Comment by pardeike** [comment]
If I get a version before Thursday I will make a release

**Comment by paco3346** [comment]
Dang you fixed that fast. I just rebuilt everything (both this and Harmony) from source and it's working great! Thanks so much!
